spring:
  config:
    import: "optional:configserver:"
  application:
    name: moonggeul

  datasource:
    url: jdbc:mysql://localhost:3306/techmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


logging.level:
  org.hibernate.SQL: debug