spring:
  config:
    import: "optional:configserver:"
  application:
    name: techmate

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_CONNECT_NAME}?authSource=${MONGO_AUTH}
      database: ${MONGO_DATABASE}
      authentication-database: ${MONGO_AUTH}
      auto-index-creation: true

logging.level:
  org.hibernate.SQL: debug

oauth:
  kakao:
    app-id: ${KAKAO_APP_ID}
    client-id: ${KAKAO_CLIENT_ID}
    redirect-url: ${KAKAO_REDIRECT_URL}
    base-url: ${KAKAO_BASE_URL}
    admin-key: ${KAKAO_ADMIN_KEY}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    redirect-url: ${GOOGLE_REDIRECT_URL}
    base-url: ${GOOGLE_BASE_URL}
    client-secret: ${GOOGLE_SECRET}

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}